language: php

sudo: true

php:
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    # add composer's global bin directory to the path
    # see: https://github.com/drush-ops/drush#install---composer
    - PATH="$PATH:$HOME/.composer/vendor/bin"

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_install:
  - export UPDATE TRAVIS_BUILD_DIR
  - BUILD_TOP=`dirname $TRAVIS_BUILD_DIR`
  - EXIT_VALUE=0
  - sudo apt-get update > /dev/null
  - composer self-update
  # Install Phantomjs prerequisites
  - sudo apt-get install -y build-essential chrpath libssl-dev libxft-dev
  - sudo apt-get install -y libfreetype6 libfreetype6-dev wget
  - sudo apt-get install -y libfontconfig1 libfontconfig1-dev
  # mail requirements

install:
  # install php packages required for running a web server from drush on php 5.6
  - sudo apt-get install -y --force-yes php5-curl php5-mysql
  # install drush
  - php -r "readfile('http://files.drush.org/drush.phar');" > drush
  - chmod +x drush
  - sudo mv drush /usr/local/bin
  # install Phantomjs
  - cd ~
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
  - sudo tar xvjf phantomjs-1.9.8-linux-x86_64.tar.bz2
  - sudo mv phantomjs-1.9.8-linux-x86_64 /usr/local/share
  - sudo ln -sf /usr/local/share/phantomjs-1.9.8-linux-x86_64/bin/phantomjs /usr/local/bin
  - nohup /usr/local/share/phantomjs --webdriver=8643 > /dev/null 2>&1 &

notifications:
  email: false

