language: php

sudo: true

php:
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    # add composer's global bin directory to the path
    # see: https://github.com/drush-ops/drush#install---composer
    - PATH="$PATH:$HOME/.composer/vendor/bin"
